/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nyilvantarto;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lireoy
 */
public class Main extends javax.swing.JFrame {

    private ArrayList<Tag> tagok;
    private ArrayList<Konyv> konyvek;
    private ArrayList<Kolcsonzes> kolcsonzesek;
    private final Adatbazis adatbazis = new Adatbazis("nyilvantartas", "root", "");

    public Main() {
        initComponents();

        tagokFrissitese();
        konyvekFrissitese();
        kolcsonzesekTablaFeltolt();
        
        // TODO: JList
        // TODO: Radio button
        // TODO: Kipipálható kis szar.
        // TODO: Lista szűrés pl rendszámra keresés
        // TODO: PrepareStatement összegányolása
        // TODO: Timestamp-el valamit (epoch time-al kapcsolatos szarok is)
    }

    private void tagokFrissitese() {
        tagokTablaFeltolt();
        kolcsonzesTagComboBoxFeltolt();
    }

    private void konyvekFrissitese() {
        konyvekTablaFeltolt();
        kolcsonzesKonyvComboBoxFeltolt();
    }

    private void tagokTablaFeltolt() {
        tagok = adatbazis.osszesTag();
        DefaultTableModel tagokTablaModel = (DefaultTableModel) tagokTabla.getModel();
        tagokTablaModel.setRowCount(0);
        for (Tag tag : tagok) {
            Object[] obj = new Object[]{tag.getId(), tag.getNev(), tag.getTelefon(), tag.getLakcim()};
            tagokTablaModel.addRow(obj);
        }
        tagokTabla.setModel(tagokTablaModel);
    }

    private void konyvekTablaFeltolt() {
        konyvek = adatbazis.osszesKonyv();
        DefaultTableModel konyvekTablaModel = (DefaultTableModel) konyvekTabla.getModel();
        konyvekTablaModel.setRowCount(0);
        for (Konyv konyv : konyvek) {
            Object[] obj = new Object[]{
                konyv.getSorozatSzam(),
                konyv.getKiado(),
                konyv.getSzerzo(),
                konyv.getCim(),
                konyv.getErtek()};
            konyvekTablaModel.addRow(obj);
        }
        konyvekTabla.setModel(konyvekTablaModel);
    }

    private void kolcsonzesekTablaFeltolt() {
        kolcsonzesek = adatbazis.osszesKolcsonzes();
        DefaultTableModel kolcsonzesekTablaModel = (DefaultTableModel) kolcsonzesekTabla.getModel();
        kolcsonzesekTablaModel.setRowCount(0);
        for (Kolcsonzes kolcsonzes : kolcsonzesek) {
            Object[] obj = new Object[]{
                kolcsonzes.getId(),
                kolcsonzes.getKonyv(),
                kolcsonzes.getTag(),
                kolcsonzes.getIdopont()};
            kolcsonzesekTablaModel.addRow(obj);
        }
        kolcsonzesekTabla.setModel(kolcsonzesekTablaModel);
    }

    private void kolcsonzesTagComboBoxFeltolt() {
        tagComboBox.removeAllItems();
        for (Tag tag : tagok) {
            tagComboBox.addItem(tag.getNev());
        }
    }

    private void kolcsonzesKonyvComboBoxFeltolt() {
        konyvComboBox.removeAllItems();
        for (Konyv konyv : konyvek) {
            konyvComboBox.addItem(konyv.getCim());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fulek = new javax.swing.JTabbedPane();
        tagokFul = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tagokTabla = new javax.swing.JTable();
        tagEltavolitGomb = new javax.swing.JButton();
        tagTablaFrissites = new javax.swing.JButton();
        konyvekFul = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        konyvekTabla = new javax.swing.JTable();
        konyvEltavolitGomb = new javax.swing.JButton();
        konyvTablaFrissites = new javax.swing.JButton();
        kolcsonzesekFul = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        kolcsonzesekTabla = new javax.swing.JTable();
        kolcsonzesEltavolitGomb = new javax.swing.JButton();
        kolcsonzesTablaFrissites = new javax.swing.JButton();
        ujTagFul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ujTagNev = new javax.swing.JTextField();
        ujTagTelefon = new javax.swing.JTextField();
        ujTagLakcim = new javax.swing.JTextField();
        tagFelvitelGomb = new javax.swing.JButton();
        ujKonyvFul = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ujKonyvSorozatSzam = new javax.swing.JTextField();
        ujKonyvKiado = new javax.swing.JTextField();
        ujKonyvSzerzo = new javax.swing.JTextField();
        ujKonyvCim = new javax.swing.JTextField();
        konyvFelvitelGomb = new javax.swing.JButton();
        ujKonyvErtek = new javax.swing.JTextField();
        kolcsonzesFul = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tagComboBox = new javax.swing.JComboBox<>();
        tagid = new javax.swing.JTextField();
        tagTelefon = new javax.swing.JTextField();
        tagLakcim = new javax.swing.JTextField();
        konyvComboBox = new javax.swing.JComboBox<>();
        konyvSzerzo = new javax.swing.JTextField();
        konyvSorozatszam = new javax.swing.JTextField();
        kolcsonzesGomb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nyilvantarto");
        setResizable(false);

        tagokTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Azonosító", "Név", "Telefon", "Lakcím"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tagokTabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tagokTabla);

        tagEltavolitGomb.setText("Eltávolítás");
        tagEltavolitGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagEltavolitGombActionPerformed(evt);
            }
        });

        tagTablaFrissites.setText("🔄");
        tagTablaFrissites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagTablaFrissitesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tagokFulLayout = new javax.swing.GroupLayout(tagokFul);
        tagokFul.setLayout(tagokFulLayout);
        tagokFulLayout.setHorizontalGroup(
            tagokFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(tagokFulLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(tagEltavolitGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(tagTablaFrissites)
                .addContainerGap())
        );
        tagokFulLayout.setVerticalGroup(
            tagokFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tagokFulLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tagokFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagEltavolitGomb)
                    .addComponent(tagTablaFrissites))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fulek.addTab("Tagok", tagokFul);

        konyvekTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sorozatszám", "Kiadó", "Szerző", "Cím", "Érték"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        konyvekTabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(konyvekTabla);

        konyvEltavolitGomb.setText("Eltávolítás");
        konyvEltavolitGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konyvEltavolitGombActionPerformed(evt);
            }
        });

        konyvTablaFrissites.setText("🔄");

        javax.swing.GroupLayout konyvekFulLayout = new javax.swing.GroupLayout(konyvekFul);
        konyvekFul.setLayout(konyvekFulLayout);
        konyvekFulLayout.setHorizontalGroup(
            konyvekFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(konyvekFulLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(konyvEltavolitGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(konyvTablaFrissites)
                .addContainerGap())
        );
        konyvekFulLayout.setVerticalGroup(
            konyvekFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(konyvekFulLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(konyvekFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konyvEltavolitGomb)
                    .addComponent(konyvTablaFrissites))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fulek.addTab("Könyvek", konyvekFul);

        kolcsonzesekTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Azonosító", "Könyv", "Tag", "Időpont"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kolcsonzesekTabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(kolcsonzesekTabla);

        kolcsonzesEltavolitGomb.setText("Eltávolítás");
        kolcsonzesEltavolitGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolcsonzesEltavolitGombActionPerformed(evt);
            }
        });

        kolcsonzesTablaFrissites.setText("🔄");
        kolcsonzesTablaFrissites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolcsonzesTablaFrissitesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kolcsonzesekFulLayout = new javax.swing.GroupLayout(kolcsonzesekFul);
        kolcsonzesekFul.setLayout(kolcsonzesekFulLayout);
        kolcsonzesekFulLayout.setHorizontalGroup(
            kolcsonzesekFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(kolcsonzesekFulLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(kolcsonzesEltavolitGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(kolcsonzesTablaFrissites)
                .addContainerGap())
        );
        kolcsonzesekFulLayout.setVerticalGroup(
            kolcsonzesekFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kolcsonzesekFulLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kolcsonzesekFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kolcsonzesEltavolitGomb)
                    .addComponent(kolcsonzesTablaFrissites))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fulek.addTab("Kölcsönzések", kolcsonzesekFul);

        jLabel1.setText("Név");

        jLabel2.setText("Telefon");

        jLabel3.setText("Lakcím");

        tagFelvitelGomb.setText("Felvitel");
        tagFelvitelGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagFelvitelGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ujTagFulLayout = new javax.swing.GroupLayout(ujTagFul);
        ujTagFul.setLayout(ujTagFulLayout);
        ujTagFulLayout.setHorizontalGroup(
            ujTagFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ujTagFulLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(ujTagFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ujTagTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ujTagFulLayout.createSequentialGroup()
                        .addGroup(ujTagFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(ujTagFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ujTagFulLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(ujTagLakcim, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ujTagFulLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ujTagNev, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ujTagFulLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(tagFelvitelGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        ujTagFulLayout.setVerticalGroup(
            ujTagFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ujTagFulLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(ujTagFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ujTagNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(ujTagFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ujTagTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(ujTagFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ujTagLakcim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(tagFelvitelGomb)
                .addGap(30, 30, 30))
        );

        fulek.addTab("Új tag felvétele", ujTagFul);

        jLabel4.setText("Sorozatszám");

        jLabel5.setText("Kiadó");

        jLabel6.setText("Szerző");

        jLabel7.setText("Cím");

        jLabel8.setText("Érték");

        konyvFelvitelGomb.setText("Felvitel");
        konyvFelvitelGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konyvFelvitelGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ujKonyvFulLayout = new javax.swing.GroupLayout(ujKonyvFul);
        ujKonyvFul.setLayout(ujKonyvFulLayout);
        ujKonyvFulLayout.setHorizontalGroup(
            ujKonyvFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ujKonyvFulLayout.createSequentialGroup()
                .addGroup(ujKonyvFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ujKonyvFulLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ujKonyvFulLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ujKonyvFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(29, 29, 29)
                .addGroup(ujKonyvFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ujKonyvSorozatSzam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ujKonyvKiado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ujKonyvSzerzo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ujKonyvCim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ujKonyvErtek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(ujKonyvFulLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(konyvFelvitelGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        ujKonyvFulLayout.setVerticalGroup(
            ujKonyvFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ujKonyvFulLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(ujKonyvFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ujKonyvSorozatSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(ujKonyvFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ujKonyvKiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(ujKonyvFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ujKonyvSzerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(ujKonyvFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ujKonyvCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(ujKonyvFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ujKonyvErtek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(konyvFelvitelGomb)
                .addGap(30, 30, 30))
        );

        fulek.addTab("Új könyv hozzáadása", ujKonyvFul);

        jLabel9.setText("Tag");

        jLabel10.setText("Könyv");

        jLabel11.setText("ID");

        jLabel12.setText("Telefon");

        jLabel13.setText("Lakcím");

        jLabel14.setText("Szerző");

        jLabel15.setText("Sorozatszám");

        tagComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        tagComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagComboBoxActionPerformed(evt);
            }
        });

        tagid.setEditable(false);

        tagTelefon.setEditable(false);

        tagLakcim.setEditable(false);

        konyvComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        konyvComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konyvComboBoxActionPerformed(evt);
            }
        });

        konyvSzerzo.setEditable(false);

        konyvSorozatszam.setEditable(false);

        kolcsonzesGomb.setText("Kölcsönzés");
        kolcsonzesGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolcsonzesGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kolcsonzesFulLayout = new javax.swing.GroupLayout(kolcsonzesFul);
        kolcsonzesFul.setLayout(kolcsonzesFulLayout);
        kolcsonzesFulLayout.setHorizontalGroup(
            kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kolcsonzesFulLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(kolcsonzesGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kolcsonzesFulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addGroup(kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(konyvSorozatszam)
                    .addComponent(konyvSzerzo)
                    .addComponent(tagLakcim)
                    .addComponent(tagTelefon)
                    .addComponent(tagComboBox, 0, 620, Short.MAX_VALUE)
                    .addComponent(konyvComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tagid))
                .addGap(60, 60, 60))
        );
        kolcsonzesFulLayout.setVerticalGroup(
            kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kolcsonzesFulLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tagComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(20, 20, 20)
                .addGroup(kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(20, 20, 20)
                .addGroup(kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagLakcim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(45, 45, 45)
                .addGroup(kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konyvComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(20, 20, 20)
                .addGroup(kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konyvSzerzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(20, 20, 20)
                .addGroup(kolcsonzesFulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konyvSorozatszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(kolcsonzesGomb)
                .addGap(30, 30, 30))
        );

        fulek.addTab("Kölcsönzés", kolcsonzesFul);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fulek, javax.swing.GroupLayout.PREFERRED_SIZE, 818, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fulek)
        );

        setSize(new java.awt.Dimension(836, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tagEltavolitGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagEltavolitGombActionPerformed
        if (tagokTabla.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Kérem válasszon ki egy tagot az eltávolításhoz!",
                    "Hiba",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int azonosito = tagok.get(tagokTabla.getSelectedRow()).getId();

        boolean sikeres = adatbazis.tagTorles(azonosito);

        if (sikeres) {
            JOptionPane.showMessageDialog(
                    this,
                    "Sikeresen törölte a tagot!",
                    "Információ",
                    JOptionPane.INFORMATION_MESSAGE
            );
            tagokFrissitese();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Sikertelen volt a tag törlése. Amennyiben rendelkezik aktív kölcsönzéssel a tag, azt nem lehet törölni.",
                    "Hiba",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_tagEltavolitGombActionPerformed

    private void konyvEltavolitGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konyvEltavolitGombActionPerformed
        if (konyvekTabla.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Kérem válasszon ki egy könyvet az eltávolításhoz!",
                    "Hiba",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int azonosito = konyvek.get(konyvekTabla.getSelectedRow()).getSorozatSzam();

        boolean sikeres = adatbazis.konyvTorles(azonosito);

        if (sikeres) {
            JOptionPane.showMessageDialog(
                    this,
                    "Sikeresen törölte a könyvet!",
                    "Információ",
                    JOptionPane.INFORMATION_MESSAGE
            );
            konyvekFrissitese();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Sikertelen volt a könyv törlése. Amennyiben aktív kölcsönzés alatt van a könyv, azt nem lehet törölni.",
                    "Hiba",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_konyvEltavolitGombActionPerformed

    private void tagTablaFrissitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagTablaFrissitesActionPerformed
        tagokFrissitese();
    }//GEN-LAST:event_tagTablaFrissitesActionPerformed

    private void kolcsonzesTablaFrissitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolcsonzesTablaFrissitesActionPerformed
        kolcsonzesekTablaFeltolt();
    }//GEN-LAST:event_kolcsonzesTablaFrissitesActionPerformed

    private void tagFelvitelGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagFelvitelGombActionPerformed
        if (ujTagNev.getText().trim().isEmpty() || ujTagTelefon.getText().trim().isEmpty()
                || ujTagLakcim.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Egy mező sem maradhat üresen!",
                    "Hiba",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        adatbazis.tagFelvitel(
                ujTagNev.getText().trim(),
                ujTagTelefon.getText().trim(),
                ujTagLakcim.getText().trim());

        JOptionPane.showMessageDialog(
                this,
                "Sikeres felvitel!",
                "Üzenet",
                JOptionPane.INFORMATION_MESSAGE
        );

        ujTagNev.setText("");
        ujTagTelefon.setText("");
        ujTagLakcim.setText("");

        tagokFrissitese();
    }//GEN-LAST:event_tagFelvitelGombActionPerformed

    private void konyvFelvitelGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konyvFelvitelGombActionPerformed
        if (ujKonyvSorozatSzam.getText().trim().isEmpty()
                || ujKonyvCim.getText().trim().isEmpty()
                || ujKonyvKiado.getText().trim().isEmpty()
                || ujKonyvSzerzo.getText().trim().isEmpty()
                || ujKonyvErtek.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Egy mező sem maradhat üresen!",
                    "Hiba",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        adatbazis.konyvFelvitel(
                ujKonyvSorozatSzam.getText().trim(),
                ujKonyvKiado.getText().trim(),
                ujKonyvSzerzo.getText().trim(),
                ujKonyvCim.getText().trim(),
                ujKonyvErtek.getText().trim());

        JOptionPane.showMessageDialog(
                this,
                "Sikeres felvitel!",
                "Üzenet",
                JOptionPane.INFORMATION_MESSAGE
        );

        ujKonyvSorozatSzam.setText("");
        ujKonyvKiado.setText("");
        ujKonyvSzerzo.setText("");
        ujKonyvCim.setText("");
        ujKonyvErtek.setText("");

        konyvekFrissitese();
    }//GEN-LAST:event_konyvFelvitelGombActionPerformed

    private void tagComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagComboBoxActionPerformed
        if (tagComboBox.getSelectedIndex() == -1) {
            return;
        }
        Tag tag = tagok.get(tagComboBox.getSelectedIndex());

        tagid.setText(String.valueOf(tag.getId()));
        tagTelefon.setText(String.valueOf(tag.getTelefon()));
        tagLakcim.setText(tag.getLakcim());
    }//GEN-LAST:event_tagComboBoxActionPerformed

    private void konyvComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konyvComboBoxActionPerformed
        if (konyvComboBox.getSelectedIndex() == -1) {
            return;
        }
        Konyv konyv = konyvek.get(konyvComboBox.getSelectedIndex());

        konyvSzerzo.setText(konyv.getSzerzo());
        konyvSorozatszam.setText(String.valueOf(konyv.getSorozatSzam()));
    }//GEN-LAST:event_konyvComboBoxActionPerformed

    private void kolcsonzesGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolcsonzesGombActionPerformed
        int tagId = tagok.get(tagComboBox.getSelectedIndex()).getId();
        int konyvId = konyvek.get(konyvComboBox.getSelectedIndex()).getSorozatSzam();

        boolean sikeres = adatbazis.kolcsonzesFelvitel(konyvId, tagId);

        if (sikeres) {
            JOptionPane.showMessageDialog(
                    this,
                    "Sikeres felvitel!",
                    "Üzenet",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Sikertelen felvitel. Győzödjön meg róla, hogy a kölcsönző tag 3 kölcsönzésnél kevesebbel rendelkezik, és a könyvet még senki más nem kölcsönözte.",
                    "Hiba",
                    JOptionPane.WARNING_MESSAGE
            );
        }
        kolcsonzesekTablaFeltolt();
    }//GEN-LAST:event_kolcsonzesGombActionPerformed

    private void kolcsonzesEltavolitGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolcsonzesEltavolitGombActionPerformed
        if (kolcsonzesekTabla.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Kérem válasszon ki egy kölcsönzést az eltávolításhoz!",
                    "Hiba",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int azonosito = kolcsonzesek.get(kolcsonzesekTabla.getSelectedRow()).getId();

        boolean sikeres = adatbazis.kolcsonzesTorles(azonosito);

        if (sikeres) {
            JOptionPane.showMessageDialog(
                    this,
                    "Sikeresen törölte a kölcsönzést!",
                    "Információ",
                    JOptionPane.INFORMATION_MESSAGE
            );
            kolcsonzesekTablaFeltolt();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Sikertelen volt a kölcsönzés törlése.",
                    "Hiba",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_kolcsonzesEltavolitGombActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane fulek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton kolcsonzesEltavolitGomb;
    private javax.swing.JPanel kolcsonzesFul;
    private javax.swing.JButton kolcsonzesGomb;
    private javax.swing.JButton kolcsonzesTablaFrissites;
    private javax.swing.JPanel kolcsonzesekFul;
    private javax.swing.JTable kolcsonzesekTabla;
    private javax.swing.JComboBox<String> konyvComboBox;
    private javax.swing.JButton konyvEltavolitGomb;
    private javax.swing.JButton konyvFelvitelGomb;
    private javax.swing.JTextField konyvSorozatszam;
    private javax.swing.JTextField konyvSzerzo;
    private javax.swing.JButton konyvTablaFrissites;
    private javax.swing.JPanel konyvekFul;
    private javax.swing.JTable konyvekTabla;
    private javax.swing.JComboBox<String> tagComboBox;
    private javax.swing.JButton tagEltavolitGomb;
    private javax.swing.JButton tagFelvitelGomb;
    private javax.swing.JTextField tagLakcim;
    private javax.swing.JButton tagTablaFrissites;
    private javax.swing.JTextField tagTelefon;
    private javax.swing.JTextField tagid;
    private javax.swing.JPanel tagokFul;
    private javax.swing.JTable tagokTabla;
    private javax.swing.JTextField ujKonyvCim;
    private javax.swing.JTextField ujKonyvErtek;
    private javax.swing.JPanel ujKonyvFul;
    private javax.swing.JTextField ujKonyvKiado;
    private javax.swing.JTextField ujKonyvSorozatSzam;
    private javax.swing.JTextField ujKonyvSzerzo;
    private javax.swing.JPanel ujTagFul;
    private javax.swing.JTextField ujTagLakcim;
    private javax.swing.JTextField ujTagNev;
    private javax.swing.JTextField ujTagTelefon;
    // End of variables declaration//GEN-END:variables
}
